#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code

awk '
$1 ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/ && $9 ~ /^[0-9]{3}$/ {
    count[$1, $9]++
}
END {
    for (key in count) {
        split(key, fields, SUBSEP)
        printf "%d %s %s\n", count[key], fields[1], fields[2]
    }
}
' | sort -nr

