#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the PID(s) of the running script
pid=$(pgrep -f 4-to_infinity_and_beyond)

# If we found any PID, kill them
if [[ -n "$pid" ]]; then
    kill "$pid"
fi

